-- Ghost in the Shell colourscheme.
-- CRT cyan on navy-black; the red "eye" is reserved for the cursor, errors and the dashboard keys.
--   vim.g.gits_transparent = true   -> let the terminal background show through
local M = {}

local c = require("gits.palette")

---@return table<string, vim.api.keyset.highlight|string>  string value = link
local function groups()
  local bg = vim.g.gits_transparent and "NONE" or c.bg
  local sidebar = vim.g.gits_transparent and "NONE" or c.bg_dark
  local punct = "#3E8A93" -- cyan, pulled back so brackets recede

  local g = {
    -- editor ---------------------------------------------------------------------------------
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg, bg = bg },
    NormalFloat = { bg = "NONE" },
    FloatBorder = { fg = c.cyan, bg = c.bg_alt },
    FloatTitle = { fg = c.bg, bg = c.cyan, bold = true },
    FloatFooter = { fg = c.muted, bg = c.bg_alt },
    Cursor = { fg = "#99ffff", bg = "#99ffff" },
    lCursor = { fg = "#99ffff", bg = "#99ffff" },
    CursorIM = { fg = "#99ffff", bg = "#99ffff" },
    TermCursor = { fg = "#99ffff", bg = "#99ffff" },
    CursorInsert = { fg = "#99ffff", bg = "#99ffff" },
    CursorReplace = { fg = "#99ffff", bg = "#99ffff" },
    CursorLine = { bg = c.bg_alt },
    CursorColumn = { bg = c.bg_alt },
    ColorColumn = { bg = c.bg_alt },
    CursorLineNr = { fg = c.cyan_hi, bold = true },
    LineNr = { fg = c.faint, bg = bg },
    LineNrAbove = { fg = c.faint },
    LineNrBelow = { fg = c.faint },
    SignColumn = { fg = c.faint, bg = bg },
    FoldColumn = { fg = c.faint, bg = bg },
    Folded = { fg = c.cyan, bg = c.bg_hl },
    EndOfBuffer = { fg = bg },
    NonText = { fg = c.line },
    Whitespace = { fg = c.line },
    SpecialKey = { fg = c.line },
    Conceal = { fg = c.muted },
    Visual = { bg = c.cyan_lo },
    VisualNOS = { bg = c.cyan_lo },
    Search = { fg = c.bg, bg = c.yellow },
    CurSearch = { fg = c.bg, bg = c.red_hi, bold = true },
    IncSearch = { fg = c.bg, bg = c.red_hi, bold = true },
    Substitute = { fg = c.bg, bg = c.red },
    MatchParen = { fg = c.red_hi, bg = c.bg_hl, bold = true },
    WinSeparator = { fg = c.line },
    VertSplit = { fg = c.line },
    Directory = { fg = c.cyan },
    Title = { fg = c.cyan_hi, bold = true },
    QuickFixLine = { bg = c.bg_hl, bold = true },
    Question = { fg = c.cyan },
    ErrorMsg = { fg = c.red },
    WarningMsg = { fg = c.yellow },
    MoreMsg = { fg = c.cyan },
    ModeMsg = { fg = c.cyan, bold = true },
    MsgArea = { fg = c.fg_dim },
    MsgSeparator = { fg = c.line, bg = c.bg_alt },
    WildMenu = { fg = c.bg, bg = c.cyan },
    Pmenu = { fg = c.fg, bg = c.bg_alt },
    PmenuSel = { fg = c.bg, bg = c.cyan, bold = true },
    PmenuKind = { fg = c.purple_hi, bg = c.bg_alt },
    PmenuKindSel = { fg = c.bg, bg = c.cyan },
    PmenuExtra = { fg = c.muted, bg = c.bg_alt },
    PmenuExtraSel = { fg = c.bg_hl, bg = c.cyan },
    PmenuSbar = { bg = c.bg_hl },
    PmenuThumb = { bg = c.cyan_lo },
    StatusLine = { fg = c.cyan, bg = c.bg_alt },
    StatusLineNC = { fg = c.muted, bg = c.bg_alt },
    WinBar = { fg = c.fg_dim, bg = bg },
    WinBarNC = { fg = c.muted, bg = bg },
    TabLine = { fg = c.fg_dim, bg = c.bg_hl },
    TabLineSel = { fg = c.bg, bg = c.cyan, bold = true },
    TabLineFill = { bg = c.bg },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },
    SpellRare = { sp = c.purple_hi, undercurl = true },

    -- diff -----------------------------------------------------------------------------------
    DiffAdd = { bg = c.diff_add },
    DiffDelete = { fg = c.red, bg = c.diff_del },
    DiffChange = { bg = c.diff_chg },
    DiffText = { bg = c.diff_txt },
    Added = { fg = c.green },
    Changed = { fg = c.blue_hi },
    Removed = { fg = c.red },

    -- syntax ---------------------------------------------------------------------------------
    Comment = { fg = c.muted, italic = true },
    Constant = { fg = c.red_hi },
    String = { fg = c.green_hi },
    Character = { fg = c.green_hi },
    Number = { fg = c.yellow },
    Boolean = { fg = c.red_hi },
    Float = { },
    Identifier = { fg = c.fg },
    Function = { fg = c.cyan_hi },
    Statement = { fg = c.purple_hi },
    Conditional = { fg = c.purple_hi },
    Repeat = { fg = c.purple_hi },
    Label = { fg = c.purple_hi },
    Operator = { fg = c.cyan },
    Keyword = { fg = c.purple_hi },
    Exception = { fg = c.purple_hi },
    PreProc = { fg = c.blue_hi },
    Include = { fg = c.blue_hi },
    Define = { fg = c.blue_hi },
    Macro = { fg = c.blue_hi },
    PreCondit = { fg = c.blue_hi },
    Type = { fg = c.blue_hi },
    StorageClass = { fg = c.blue_hi },
    Structure = { fg = c.blue_hi },
    Typedef = { fg = c.blue_hi },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.cyan_hi },
    Tag = { fg = c.cyan },
    Delimiter = { fg = punct },
    SpecialComment = { fg = c.cyan_lo, italic = true },
    Debug = { fg = c.red },
    Underlined = { fg = c.cyan_hi, underline = true },
    Ignore = { fg = c.faint },
    Error = { fg = c.red },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    -- treesitter -----------------------------------------------------------------------------
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.red_hi },
    ["@variable.parameter"] = { fg = c.yellow_hi },
    ["@variable.parameter.builtin"] = { fg = c.yellow_hi },
    ["@variable.member"] = { fg = c.fg_dim },
    ["@property"] = { fg = c.fg_dim },
    ["@field"] = { fg = c.fg_dim },
    ["@constant"] = { fg = c.red_hi },
    ["@constant.builtin"] = { fg = c.red_hi },
    ["@constant.macro"] = { fg = c.blue_hi },
    ["@module"] = { fg = c.fg_dim },
    ["@module.builtin"] = { fg = c.fg_dim },
    ["@label"] = { fg = c.purple_hi },
    ["@string"] = { fg = c.green_hi },
    ["@string.documentation"] = { fg = c.muted },
    ["@string.escape"] = { fg = c.cyan_hi },
    ["@string.regexp"] = { fg = c.cyan_hi },
    ["@string.special"] = { fg = c.cyan_hi },
    ["@string.special.url"] = { fg = c.cyan_hi, underline = true },
    ["@character"] = { fg = c.green_hi },
    ["@number"] = { fg = c.yellow },
    ["@number.float"] = { fg = c.yellow },
    ["@boolean"] = { fg = c.red_hi },
    ["@function"] = { fg = c.cyan_hi },
    ["@function.builtin"] = { fg = c.cyan },
    ["@function.call"] = { fg = c.cyan_hi },
    ["@function.macro"] = { fg = c.blue_hi },
    ["@function.method"] = { fg = c.cyan_hi },
    ["@function.method.call"] = { fg = c.cyan_hi },
    ["@constructor"] = { fg = c.blue_hi },
    ["@operator"] = { fg = c.cyan },
    ["@keyword"] = { fg = c.purple_hi },
    ["@keyword.function"] = { fg = c.purple_hi },
    ["@keyword.return"] = { fg = c.purple_hi, bold = true },
    ["@keyword.operator"] = { fg = c.purple_hi },
    ["@keyword.import"] = { fg = c.blue_hi },
    ["@keyword.exception"] = { fg = c.purple_hi },
    ["@type"] = { fg = c.blue_hi },
    ["@type.builtin"] = { fg = c.blue },
    ["@type.definition"] = { fg = c.blue_hi },
    ["@attribute"] = { fg = c.blue_hi },
    ["@attribute.builtin"] = { fg = c.blue_hi },
    ["@punctuation"] = { fg = punct },
    ["@punctuation.delimiter"] = { fg = punct },
    ["@punctuation.bracket"] = { fg = punct },
    ["@punctuation.special"] = { fg = c.cyan },
    ["@tag"] = { fg = c.cyan },
    ["@tag.attribute"] = { fg = c.fg_dim },
    ["@tag.delimiter"] = { fg = punct },
    ["@tag.builtin"] = { fg = c.cyan },
    ["@comment"] = { fg = c.muted, italic = true },
    ["@comment.documentation"] = { fg = c.muted, italic = true },
    ["@comment.error"] = { fg = c.bg, bg = c.red, bold = true },
    ["@comment.warning"] = { fg = c.bg, bg = c.yellow, bold = true },
    ["@comment.todo"] = { fg = c.bg, bg = c.blue_hi, bold = true },
    ["@comment.note"] = { fg = c.bg, bg = c.cyan, bold = true },
    ["@markup"] = { fg = c.fg },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.cyan_hi, bold = true },
    ["@markup.heading.1"] = { fg = c.cyan_hi, bold = true },
    ["@markup.heading.2"] = { fg = c.cyan, bold = true },
    ["@markup.heading.3"] = { fg = c.blue_hi, bold = true },
    ["@markup.heading.4"] = { fg = c.purple_hi, bold = true },
    ["@markup.heading.5"] = { fg = c.green_hi, bold = true },
    ["@markup.heading.6"] = { fg = c.yellow, bold = true },
    ["@markup.quote"] = { fg = c.muted, italic = true },
    ["@markup.math"] = { fg = c.yellow },
    ["@markup.link"] = { fg = c.cyan },
    ["@markup.link.label"] = { fg = c.cyan_hi },
    ["@markup.link.url"] = { fg = c.blue_hi, underline = true },
    ["@markup.raw"] = { fg = c.green_hi },
    ["@markup.raw.block"] = { fg = c.fg_dim },
    ["@markup.list"] = { fg = c.cyan },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.muted },
    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.blue_hi },

    -- lsp ------------------------------------------------------------------------------------
    LspReferenceText = { bg = c.bg_hl },
    LspReferenceRead = { bg = c.bg_hl },
    LspReferenceWrite = { bg = c.bg_hl, underline = true },
    LspReferenceTarget = { bg = c.bg_hl },
    LspInlayHint = { fg = c.faint, bg = c.bg_alt, italic = true },
    LspCodeLens = { fg = c.faint },
    LspCodeLensSeparator = { fg = c.faint },
    LspSignatureActiveParameter = { fg = c.yellow, bold = true },
    ["@lsp.type.comment"] = {}, -- keep treesitter's comment colours
    ["@lsp.type.variable"] = {}, -- and its variable colours (semantic tokens would flatten them)
    ["@lsp.type.parameter"] = "@variable.parameter",
    ["@lsp.type.property"] = "@property",
    ["@lsp.type.enumMember"] = "@constant",
    ["@lsp.type.namespace"] = "@module",
    ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
    ["@lsp.typemod.variable.readonly"] = "@constant",

    -- diagnostics ----------------------------------------------------------------------------
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.cyan },
    DiagnosticHint = { fg = c.green },
    DiagnosticOk = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.red_hi, bg = c.diff_del },
    DiagnosticVirtualTextWarn = { fg = c.yellow_hi, bg = "#2A230E" },
    DiagnosticVirtualTextInfo = { fg = c.cyan_hi, bg = c.diff_add },
    DiagnosticVirtualTextHint = { fg = c.green_hi, bg = c.diff_add },
    DiagnosticVirtualTextOk = { fg = c.green_hi, bg = c.diff_add },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.green, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticUnnecessary = { fg = c.faint },
    DiagnosticDeprecated = { sp = c.muted, strikethrough = true },

    -- git ------------------------------------------------------------------------------------
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.blue_hi },
    GitSignsDelete = { fg = c.red },
    GitSignsTopdelete = { fg = c.red },
    GitSignsChangedelete = { fg = c.yellow },
    GitSignsUntracked = { fg = c.purple_hi },
    GitSignsAddInline = { bg = c.diff_txt },
    GitSignsDeleteInline = { bg = c.diff_del },
    GitSignsChangeInline = { bg = c.diff_txt },
    GitSignsCurrentLineBlame = { fg = c.faint, italic = true },

    -- snacks ---------------------------------------------------------------------------------
    SnacksNormal = { fg = c.fg, bg = c.bg_alt },
    SnacksWinBar = { fg = c.cyan, bg = c.bg_alt },
    SnacksDashboardNormal = { fg = c.fg, bg = bg },
    SnacksDashboardHeader = { fg = c.cyan },
    SnacksDashboardIcon = { fg = c.cyan },
    SnacksDashboardKey = { fg = c.red_hi, bold = true },
    SnacksDashboardDesc = { fg = c.fg },
    SnacksDashboardFooter = { fg = c.muted },
    SnacksDashboardSpecial = { fg = c.cyan },
    SnacksDashboardDir = { fg = c.muted },
    SnacksDashboardFile = { fg = c.fg },
    SnacksDashboardTitle = { fg = c.cyan, bold = true },
    SnacksDashboardTerminal = { fg = c.fg },
    -- dashboard art (see lua/plugins/gits.lua)
    GitsArt = { fg = c.cyan },
    GitsArtHair = { fg = c.cyan_lo },
    GitsArtEye = { fg = c.white, bold = true },
    GitsArtClip = { fg = c.red_hi },
    GitsFrame = { fg = c.cyan_lo },
    GitsFrameText = { fg = c.cyan },
    SnacksIndent = { fg = c.line },
    SnacksIndentScope = { fg = c.cyan_lo },
    SnacksIndentChunk = { fg = c.cyan_lo },
    SnacksPickerBorder = { fg = c.cyan, bg = c.bg_alt },
    SnacksPickerTitle = { fg = c.bg, bg = c.cyan, bold = true },
    SnacksPickerDir = { fg = c.muted },
    SnacksPickerPathHidden = { fg = c.muted },
    SnacksPickerMatch = { fg = c.cyan_hi, bold = true },
    SnacksPickerSelected = { fg = c.red_hi },
    SnacksPickerPrompt = { fg = c.red_hi },
    SnacksPickerListCursorLine = { bg = c.bg_hl },
    SnacksPickerPreviewCursorLine = { bg = c.bg_hl },
    SnacksInputBorder = { fg = c.cyan, bg = c.bg_alt },
    SnacksInputTitle = { fg = c.bg, bg = c.cyan, bold = true },
    SnacksInputIcon = { fg = c.cyan },
    SnacksNotifierBorderError = { fg = c.red, bg = c.bg_alt },
    SnacksNotifierBorderWarn = { fg = c.yellow, bg = c.bg_alt },
    SnacksNotifierBorderInfo = { fg = c.cyan, bg = c.bg_alt },
    SnacksNotifierBorderDebug = { fg = c.muted, bg = c.bg_alt },
    SnacksNotifierBorderTrace = { fg = c.purple_hi, bg = c.bg_alt },
    SnacksNotifierTitleError = { fg = c.red },
    SnacksNotifierTitleWarn = { fg = c.yellow },
    SnacksNotifierTitleInfo = { fg = c.cyan },
    SnacksNotifierTitleDebug = { fg = c.muted },
    SnacksNotifierTitleTrace = { fg = c.purple_hi },
    SnacksNotifierIconError = { fg = c.red },
    SnacksNotifierIconWarn = { fg = c.yellow },
    SnacksNotifierIconInfo = { fg = c.cyan },
    SnacksNotifierIconDebug = { fg = c.muted },
    SnacksNotifierIconTrace = { fg = c.purple_hi },

    -- which-key ------------------------------------------------------------------------------
    WhichKey = { fg = c.cyan },
    WhichKeyGroup = { fg = c.purple_hi },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.muted },
    WhichKeyValue = { fg = c.muted },
    WhichKeyIcon = { fg = c.cyan },
    WhichKeyBorder = { fg = c.cyan, bg = c.bg_alt },
    WhichKeyTitle = { fg = c.bg, bg = c.cyan, bold = true },
    WhichKeyNormal = { fg = c.fg, bg = c.bg_alt },

    -- completion (blink.cmp) -----------------------------------------------------------------
    BlinkCmpMenu = { fg = c.fg, bg = c.bg_alt },
    BlinkCmpMenuBorder = { fg = c.cyan, bg = c.bg_alt },
    BlinkCmpMenuSelection = { fg = c.bg, bg = c.cyan, bold = true },
    BlinkCmpScrollBarThumb = { bg = c.cyan_lo },
    BlinkCmpScrollBarGutter = { bg = c.bg_hl },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.muted, strikethrough = true },
    BlinkCmpLabelDetail = { fg = c.muted },
    BlinkCmpLabelDescription = { fg = c.muted },
    BlinkCmpLabelMatch = { fg = c.cyan_hi, bold = true },
    BlinkCmpKind = { fg = c.purple_hi },
    BlinkCmpSource = { fg = c.muted },
    BlinkCmpGhostText = { fg = c.faint },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg_alt },
    BlinkCmpDocBorder = { fg = c.cyan, bg = c.bg_alt },
    BlinkCmpDocSeparator = { fg = c.line, bg = c.bg_alt },
    BlinkCmpDocCursorLine = { bg = c.bg_hl },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg_alt },
    BlinkCmpSignatureHelpBorder = { fg = c.cyan, bg = c.bg_alt },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.yellow, bold = true },

    -- noice ----------------------------------------------------------------------------------
    NoiceCmdline = { fg = c.fg, bg = c.bg_alt },
    NoiceCmdlineIcon = { fg = c.cyan },
    NoiceCmdlineIconSearch = { fg = c.yellow },
    NoiceCmdlinePopup = { fg = c.fg, bg = c.bg_alt },
    NoiceCmdlinePopupBorder = { fg = c.cyan, bg = c.bg_alt },
    NoiceCmdlinePopupBorderSearch = { fg = c.yellow, bg = c.bg_alt },
    NoiceCmdlinePopupTitle = { fg = c.cyan_hi, bg = c.bg_alt },
    NoiceConfirmBorder = { fg = c.red_hi, bg = c.bg_alt },
    NoicePopupmenu = { fg = c.fg, bg = c.bg_alt },
    NoicePopupmenuBorder = { fg = c.cyan, bg = c.bg_alt },
    NoicePopupmenuSelected = { fg = c.bg, bg = c.cyan },
    NoiceMini = { fg = c.fg_dim, bg = c.bg_alt },
    NoiceLspProgressTitle = { fg = c.muted },
    NoiceLspProgressClient = { fg = c.cyan },
    NoiceLspProgressSpinner = { fg = c.cyan_hi },

    -- neo-tree -------------------------------------------------------------------------------
    NeoTreeNormal = { fg = c.fg_dim, bg = sidebar },
    NeoTreeNormalNC = { fg = c.fg_dim, bg = sidebar },
    NeoTreeEndOfBuffer = { fg = sidebar, bg = sidebar },
    NeoTreeWinSeparator = { fg = c.line, bg = sidebar },
    NeoTreeFloatBorder = { fg = c.cyan, bg = c.bg_alt },
    NeoTreeFloatTitle = { fg = c.bg, bg = c.cyan, bold = true },
    NeoTreeTitleBar = { fg = c.bg, bg = c.cyan, bold = true },
    NeoTreeRootName = { fg = c.cyan_hi, bold = true },
    NeoTreeDirectoryName = { fg = c.fg },
    NeoTreeDirectoryIcon = { fg = c.cyan },
    NeoTreeFileName = { fg = c.fg_dim },
    NeoTreeFileNameOpened = { fg = c.cyan_hi },
    NeoTreeIndentMarker = { fg = c.line },
    NeoTreeExpander = { fg = c.cyan_lo },
    NeoTreeDotfile = { fg = c.muted },
    NeoTreeHiddenByName = { fg = c.muted },
    NeoTreeDimText = { fg = c.faint },
    NeoTreeGitAdded = { fg = c.green },
    NeoTreeGitModified = { fg = c.yellow },
    NeoTreeGitDeleted = { fg = c.red },
    NeoTreeGitConflict = { fg = c.red_hi, bold = true },
    NeoTreeGitUntracked = { fg = c.purple_hi },
    NeoTreeGitIgnored = { fg = c.muted },
    NeoTreeGitStaged = { fg = c.green_hi },
    NeoTreeGitUnstaged = { fg = c.yellow },

    -- flash / trouble / todo / misc ----------------------------------------------------------
    FlashBackdrop = { fg = c.faint },
    FlashLabel = { fg = c.bg, bg = c.red_hi, bold = true },
    FlashMatch = { fg = c.cyan_hi, bg = c.bg_hl },
    FlashCurrent = { fg = c.bg, bg = c.yellow },
    FlashPrompt = { fg = c.fg, bg = c.bg_alt },
    TroubleNormal = { fg = c.fg, bg = sidebar },
    TroubleNormalNC = { fg = c.fg, bg = sidebar },
    TroubleCount = { fg = c.bg, bg = c.cyan },
    TroubleText = { fg = c.fg_dim },
    TroubleIndent = { fg = c.line },
    TroublePos = { fg = c.muted },
    TodoBgFIX = { fg = c.bg, bg = c.red, bold = true },
    TodoBgHACK = { fg = c.bg, bg = c.yellow, bold = true },
    TodoBgNOTE = { fg = c.bg, bg = c.cyan, bold = true },
    TodoBgPERF = { fg = c.bg, bg = c.purple_hi, bold = true },
    TodoBgTEST = { fg = c.bg, bg = c.purple_hi, bold = true },
    TodoBgTODO = { fg = c.bg, bg = c.blue_hi, bold = true },
    TodoBgWARN = { fg = c.bg, bg = c.yellow, bold = true },
    TodoFgFIX = { fg = c.red },
    TodoFgHACK = { fg = c.yellow },
    TodoFgNOTE = { fg = c.cyan },
    TodoFgPERF = { fg = c.purple_hi },
    TodoFgTEST = { fg = c.purple_hi },
    TodoFgTODO = { fg = c.blue_hi },
    TodoFgWARN = { fg = c.yellow },
    MiniIconsAzure = { fg = c.blue_hi },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.cyan },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.fg_dim },
    MiniIconsOrange = { fg = c.red_hi },
    MiniIconsPurple = { fg = c.purple_hi },
    MiniIconsRed = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },

    -- lazy / mason ---------------------------------------------------------------------------
    LazyNormal = { fg = c.fg, bg = c.bg_alt },
    LazyH1 = { fg = c.bg, bg = c.cyan, bold = true },
    LazyH2 = { fg = c.cyan_hi, bold = true },
    LazyButton = { fg = c.fg_dim, bg = c.bg_hl },
    LazyButtonActive = { fg = c.bg, bg = c.cyan, bold = true },
    LazySpecial = { fg = c.cyan },
    LazyProgressDone = { fg = c.cyan },
    LazyProgressTodo = { fg = c.line },
    LazyReasonPlugin = { fg = c.cyan },
    LazyCommit = { fg = c.green },
    LazyDimmed = { fg = c.muted },
    MasonNormal = { fg = c.fg, bg = c.bg_alt },
    MasonHeader = { fg = c.bg, bg = c.cyan, bold = true },
    MasonHeaderSecondary = { fg = c.bg, bg = c.red_hi, bold = true },
    MasonHighlight = { fg = c.cyan },
    MasonHighlightBlock = { fg = c.bg, bg = c.cyan },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.cyan, bold = true },
    MasonMuted = { fg = c.muted },
    MasonMutedBlock = { fg = c.fg_dim, bg = c.bg_hl },

    -- dap / neotest --------------------------------------------------------------------------
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapBreakpointRejected = { fg = c.muted },
    DapLogPoint = { fg = c.cyan },
    DapStopped = { fg = c.green },
    DapStoppedLine = { bg = c.diff_add },
    NeotestPassed = { fg = c.green },
    NeotestFailed = { fg = c.red },
    NeotestRunning = { fg = c.yellow },
    NeotestSkipped = { fg = c.cyan },
    NeotestTest = { fg = c.fg_dim },
    NeotestNamespace = { fg = c.purple_hi },
    NeotestFile = { fg = c.cyan },
    NeotestDir = { fg = c.blue_hi },
    NeotestFocused = { bold = true, underline = true },
    NeotestIndent = { fg = c.line },
    NeotestExpandMarker = { fg = c.cyan_lo },
    NeotestAdapterName = { fg = c.red_hi, bold = true },
    NeotestWinSelect = { fg = c.cyan },
    NeotestMarked = { fg = c.yellow },
    NeotestTarget = { fg = c.red_hi },

    -- markdown -------------------------------------------------------------------------------
    RenderMarkdownH1 = { fg = c.cyan_hi, bold = true },
    RenderMarkdownH2 = { fg = c.cyan, bold = true },
    RenderMarkdownH3 = { fg = c.blue_hi, bold = true },
    RenderMarkdownH4 = { fg = c.purple_hi, bold = true },
    RenderMarkdownH5 = { fg = c.green_hi, bold = true },
    RenderMarkdownH6 = { fg = c.yellow, bold = true },
    RenderMarkdownH1Bg = { bg = c.bg_hl },
    RenderMarkdownH2Bg = { bg = c.bg_alt },
    RenderMarkdownH3Bg = { bg = c.bg_alt },
    RenderMarkdownH4Bg = { bg = c.bg_alt },
    RenderMarkdownH5Bg = { bg = c.bg_alt },
    RenderMarkdownH6Bg = { bg = c.bg_alt },
    RenderMarkdownCode = { bg = c.bg_alt },
    RenderMarkdownCodeInline = { fg = c.green_hi, bg = c.bg_alt },
    RenderMarkdownBullet = { fg = c.cyan },
    RenderMarkdownQuote = { fg = c.muted },
    RenderMarkdownLink = { fg = c.cyan },
    RenderMarkdownTableHead = { fg = c.cyan },
    RenderMarkdownTableRow = { fg = c.fg_dim },
    RenderMarkdownDash = { fg = c.line },
    RenderMarkdownChecked = { fg = c.green },
    RenderMarkdownUnchecked = { fg = c.muted },
  }

  return g
end

local function terminal_colors()
  local t = {
    c.bg_hl, c.red, c.green, c.yellow, c.blue, c.purple, c.cyan, c.fg_dim,
    c.cyan_lo, c.red_hi, c.green_hi, c.yellow_hi, c.blue_hi, c.purple_hi, c.cyan_hi, c.white,
  }
  for i, color in ipairs(t) do
    vim.g["terminal_color_" .. (i - 1)] = color
  end
end

function M.load()
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.o.background = "dark"
  vim.g.colors_name = "gits"

  for name, spec in pairs(groups()) do
    if type(spec) == "string" then
      vim.api.nvim_set_hl(0, name, { link = spec })
    else
      vim.api.nvim_set_hl(0, name, spec)
    end
  end
  terminal_colors()
end

M.palette = c

return M
